name: my_app
description: "A new Flutter project with enhanced UI/UX and theme support."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Icons & fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0

  # State management
  provider: ^6.1.5

  # Toast messages
  fluttertoast: ^8.2.2

  # Optional animations
  animations: ^2.0.6
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_analytics: ^12.0.1
  package_info_plus: ^9.0.0

  # Chatbot dependencies
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  go_router: ^16.3.0
  firebase_app_check: ^0.4.1+2
  firebase_ai: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  
  assets:
    - .env                
    - assets/images/
    - assets/google_fonts/
